homework_01:
  color: [148, 24, 248]          # RGB цвет точки
  radius:  5                     # размеры точки
  transform_size: [300, 300]
  cam_frame: [640, 480]
  fps: 15
  hue_range: [0, 359]
  saturation_range: [0, 1]
  contrast_range: [0, 1]
  brightness_range: [0, 1]