homework_01:
  color: [148, 24, 248]          # RGB цвет точки
  radius:  5                     # размеры точки
  transform_size: [300, 300]
  cam_frame: [640, 480]
  fps: 15
  hue_range: [0, 359]
  saturation_range: [0, 1]
  contrast_range: [0, 1]
  brightness_range: [0, 1]

homework_02:
  image_path: 'data/saturn_rings.png'

homework_03:
  input_image_path: data/puppy.png
  output_image_path: data/output.png
  opencv_output_image_path: data/cv_output.png
  sigma_space: 15
  sigma_color: 15

homework_04:
  # Input image
  input_image: data/building.png
  # Marr-Hildreth edge detection
  sigma: 3.5
  thresh_percent: 0.2 # T = thresh_percent * LoG.max()
  # RANSAC
  threshold: 5
  max_trials: 5000
  seed: 0xC0FFEE
  # Output images
  output_image: data/line_ransac.jpg
  output_edges: data/marr_hildreth_edges.jpg
